### ISSUE TITLE
Add basic exclude/include expression support

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcztools#44]
bcftools has a mini-language of [expressions](https://samtools.github.io/bcftools/bcftools.html#expressions) which support inclusion/exclusion of variants in the output via the -i and -e operators.

We would like to support a small subset of this initially, so that we can support the query that we used in the VCF Zarr preprint ( ``bcftools view -I –include "FORMAT/DP>10 & FORMAT/GQ>20``).

Supporting the entire mini-language is probably a non-goal, and we should restrict to supporting pieces of it as we go as they are needed. Nonetheless, some initial analysis on what's involved in supporting the various aspects of the language would be very helpful.

**Comment by Will-Tyler** [comment]
I was able to look at this issue today and will use this comment to collect my thoughts.

### Overview

`vcztools view` reads a VCF Zarr object and outputs the object's contents in VCF format. The user should be able to filter which variant sites are output using a subset of the [filtering expression language](https://samtools.github.io/bcftools/bcftools.html#expressions) that bcftools implements. The implementation should easily allow other developers to expand the supported expression language without having to redo part or all of the implementation.

The VCF Zarr publication contains an [example](https://github.com/sgkit-dev/vcf-zarr-publication/blob/main/gel_example/Comparison-vcfzarr.ipynb) of how a filter might actually be computed.

### Approach

The implementation will consist of two components: a parser and an evaluator. The parser converts the filter expression string into a syntax tree whose structure and values represent the operations that comprise the filter. The evaluator processes the VCF Zarr data and computes a boolean array that indicates which variant sites match the expression. vcztools builds the evaluator using the filter expression syntax tree. If the user supplies the filter expression using an `--include` option, then vcztools includes the matching variant sites in the output. On the other hand, if the user uses `--exclude`, then the matching variant sites are excluded from the output.

The evaluator will operate on the data chunks to produce a variant mask for each chunk. `c_chunk_to_vcf` seems to be the right place to perform this task.

### Parser

I am inclined to use [PyParsing](https://pyparsing-docs.readthedocs.io/en/latest/) to implement the parser. PyParsing includes a Pythonic interface for defining the grammar and can create a tree structure using [`Group`](https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#special-subclasses). Based on the description of the expression language and my experience with PyParsing, I think that PyParsing is able to support the full language.

There are other options and many are listed on the [lark README](https://github.com/lark-parser/lark?tab=readme-ov-file). PyParsing is not the fastest parser according to the benchmark on the README. However, I do not imagine the filtering expressions will be so large that the parsing time is significant.

### Evaluator

vcztools can build the evaluator based on the syntax tree by composing functions that return boolean arrays indicating which variant sites the filter expression matches, resulting in a single evaluator function that computes which variant sites match the expression.

### Considerations

#### Filtering samples as well

If the user specifies a subset of samples to include (using the `--samples` option), `vcztools view` should still compute the filter expressions using full set of samples to match the behavior of `bcftools view` (see [here](https://samtools.github.io/bcftools/bcftools.html#view)).

#### Including and excluding

vcztools should not allow the user to provide both an `--include` expression and an `--exclude` expression, as it is not clear how to handle variant sites that are both included and excluded. This would match the behavior of `bcftools view`.

---

Tagging @tomwhite, who is also working on vcztools. I don't have any immediate questions, but I would certainly welcome your input if you are interested!

**Comment by tomwhite** [comment]
This sounds like an excellent plan @Will-Tyler!

It would be good to try implementing something end-to-end for the query that Jerome mentioned, and then build out the expression support over time.

A couple of things I also wondered about, although they may come into the category of premature optimization:
1.  We currently use regions and targets to build a mask for variant selection. It would be good if inclusion/exclusion of variants was combined with that mask so that we can avoid subsetting each field for regions/targets first, then performing a second subsetting operation for inclusion/exclusion. (But maybe the performance increase is not significant, and/or we do it later.)
2. It would be nice to retrieve only the fields being filtered first, then compute the variant selection from the filter, since if no variants in a chunk match there is no need to retrieve any of the remaining fields.

**Comment by Will-Tyler** [comment]
Thank you for adding your thoughts! Just wanted to note that I am working on the implementation now and should have a pull request soon.
