### ISSUE TITLE
Add query command with basic `-f/--format` support

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/vcztools#50]
For example:

```
vcztools query -f '%POS\n' sample.vcz
```

Don't need looping over samples (`[]` notation) yet: https://samtools.github.io/bcftools/bcftools.html#query

**Comment by Will-Tyler** [comment]
I would like to get started on this issue. I am going to try a similar approach to #49. That is, using PyParsing to create a parser that produces a syntax tree representing the query format and then producing a function based on the syntax tree that takes a chunk and returns the query results in the specified format.
