### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/vcztools#55]
It would be good to have some tests to check the performance of various vcztools commands. The thing to check is that running highly-selective queries (i.e. ones that just return a few records) on large datasets is fast.

They could be like the ones @jeromekelleher ran in https://github.com/sgkit-dev/vcztools/pull/8. These are not amenable to running on CI, so it's probably fine to have some instructions to run them manually on 1000G chromosome 2 or 20 data.

**Comment by jeromekelleher** [comment]
That would be excellent. I think a simple script that runs some commands, and outputs timings and output rate (Mb/s) for vcztools and bcftools would be sufficient. We don't need anything elaborate.

**Comment by Will-Tyler** [comment]
We have talked about performance on some of my pull requests, which has me interested in working on this. I am thinking about implementing something similar to the performance benchmarks in the VCF Zarr publication project.

We would have a separate folder, `performance`, in this project with a Makefile to put together the test data, which would go in a sub-folder, `performance/data`. There would be a list of commands to test and a script and/or make target to run the performance tests. The performance tests would compare the time and throughput rate between vcztools and bcftools for each of the comands.

This setup should make the performance tests reproducible and easy-to-run.

I am thinking to use the same simulated data from the VCF Zarr publication. Let me know if there is a better approach.

I also wonder if it would be beneficial to report the memory usage. I looked into this briefly but did not find a convenient tool to summarize the memory usage. Let me know if you have ideas.

**Comment by jeromekelleher** [comment]
I like it @Will-Tyler, sounds like a great plan! We probably don't need enormous datasets and realism isn't important at all. Simulations from [stdpopsim](https://popsim-consortium.github.io/stdpopsim-docs/main/index.html) will be fine, e.g.

```
$ stdpopsim HomSap -c chr22 -o sim_10k.ts pop_0:10000
$ tskit vcf sim_10k.ts | bgzip > sim_10k.vcf.gz
```
