### ISSUE TITLE
vcztools query: support looping over samples

### ISSUE THREAD

**Issue by Will-Tyler** [sgkit-dev/vcztools#83]
### Description

This task is to support format fields in the `vcztool query` CLI. Format fields must be enclosed in square brackets to loop over all the samples. `vcztools query` is based on `bcftools query`.

The `-f` option in `vcztools query` was added in #64.

### Example

```
bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE=%GT]\n' file.vcf.gz
```

This example from `bcftools query` illustrates using square brackets to print the sample ID, `%SAMPLE`, and the genotype, `%GT`, for all samples. We want to support this functionality in `vcztools query` as well.

### References

- [bcftools query](https://samtools.github.io/bcftools/bcftools.html#query)
- #64
  - This pull request adds the `-f` option to `vcztools query`.

**Comment by jeromekelleher** [comment]
This sounds great @Will-Tyler! Just to note that this is definitely a case where we'd want to pre-filter before fetching data from Zarr, unless the bcftools semantics bars us from doing so.
